* Voorpret
** Locaties
 Moeten we nu doen
*** Baracuda
*** MJU
*** Andere vette locaties
We kunnen hele vette locaties krijgen SVO bar, academie gebouw als we ver genoeg
vooruit plannen.

* Notulen 
Goedgekeurd. 
- paar zinnen die niet volledig zijn.

* Postronde
** Pepijne
   SVO. Is de nieuwe Assesor. 
** Bart
   We kunnen bij hem terecht voor faciltiair, pasjes, etc.
** Vraag over introductie
   Paar zinnen over terugsturen.
** STUF
   Heeft zich geintroduceerd. We kunnen drie keer of 5x geld van hun krijgen als we promo doen.
** 

* Actiepunten vorige week
** DONE Stefan [/]
   CLOSED: [2023-09-19 Tue 13:26]
- [X] Beleidsplan / HR dingen uitgewerkt die we hebben beloofd. In een bestand gezet. Staat in de werkdocumenten map.
- [X]Autarkeia terug gemailed. -> datum prikker invullen.  
- [X] Vertrouwenspersoon curus is gemailed.
- [X] Fuf x Albion 19 toch wel onhandig hun voorkeur is 26. 
** TODO Max [/]
- [X] Rondvragen naar nieuwe stamkroeg, weten ze wel maar gaat nog lastig. 
- [ ] Aanvraag bestuursbeurs
** TODO Stijn [/] 
- [ ] Activiteiten agenda nog niet gedaan.
- [ ] promo dingen komende twee weken 
  + [ ] filo cafe 26 sep
    - [ ] Spreker regelen
    - [ ] promo regelen
** DONE Philip [/]
   CLOSED: [2023-09-19 Tue 13:35]
- [X] Giullia Spammen.
- [X] Afspraak maken.

* Postmortem commissie markt
Wat ging er goed, Wat ging er fout. 

** Wat kan er beter
- Doe het op een dag dat de sjaars college hebben, nadat ze college hebben.
- Mischien werkt de vorm toch niet helemaal voor de FUF. Is dit een effectief middel?
  - Meer naar mensen toe?
  - Stijn en Max vragen zich af of het onder de BBQ kan. 
- Mischien hebben we niet genoeg promo gedaan? Wisten ze wel of het aan de gang was?

* Postmortem BBQ
Was leuk. Niet alle bestuursleden waren aanwezig.

- Misschien een eindtijd aangeven van tevoren? (Stefan zat er nog tot drie uur snachs de volgende dag).
- Geld, kan max nog gaan regelen. Hopelijk komt die overdracht van Stefan snel.

** Overschot
- Er waren 14 burgers, en een kilo tomaat, een zak sla en nog veel paprika. 
  - Grootste deel is weggegeven. 
- Er bleef bier over. Hokbier is bijna op. 

** Les
Zorg dat je dicht bij een WC zit. 

* Onderwijs commissie
Er was ooit een jaarvertegenwoordiging. JVT. Studenten van allerlei
verschillende plekken maxter bachelor, komen bij elkaar om te raten over wat ze
van het onderwijs vinden. Werdt georganiseerd door onderwijs sec. voor de OC. OC
ging dan luisteren. Afgelopen twee jaar is dit niet gebeurd (volgens OC). Floris
heeft het niet gedaan hebben. Daniel heeft het geprobeerd, maar schijnt niet
gelukt te zijn (volgens OC). OC zegt dat heel veel studies het doen dus zouden
we wel gewoon moeten doen. Victor Smit zei tegen axel dat de band te wateig is
geworden, maar is niks van gekomen.

We doen het of we doen het niet. 

-> Babbelen met victor.

* BLOCKED Aanpassen beleidsplan
We moeten wachten op de notulen van de ALV. BLOCKED.

* Vidius afspraak maken
Pnyx / Princeton laan op Uithof. (Vgm bestuursgebouw). 

Vrijdag de dertiende (oktober) van half 1 tot half 2. 


* Actiepunten vooruit
** Stijn [/]
- [ ] Babbelen met victor over JVT. 
** Stefan [/]
- [ ] Vidius daadwerkelijk inplannen. 
** Max [/] 
- [ ] Rekening overdracht
- [ ] Bestuursbeurs
** Philip [/] 
- [ ] Antwoord brasbrief schrijven.


* Vidus prikken
Een datum samen.


* Vaststellen agenda
